/*
 * Browsertrix Custom Behavior: API Pagination Chain Hunter
 * Version: 0.3.0 (2026-09-30)
 *
 * Design goals:
 * - Near-zero work on ordinary pages.
 * - Does NOT replace autoscroll/site-specific behaviors: isMatch() is always false.
 * - Hooks fetch() and XMLHttpRequest as early as Browsertrix allows via onPageInit().
 * - Parses JSON only when content/URL looks API-relevant.
 * - Also detects strong pagination links in HTML returned by fetch/XHR (rel=next,
 *   Blogger older-post links, Webflow pagination, and a small generic pager set).
 * - Detects continuation signatures, follows GET-style chains to exhaustion,
 *   and also supports common JSON POST / GraphQL cursor patterns when the
 *   original request body can be safely cloned and modified.
 * - Fetches media/document URLs found in JSON so Browsertrix can record them.
 * - Polite continuation crawling: 8-12 seconds of random spacing between
 *   generated requests to the same API endpoint, shared across concurrent chains.
 *
 * IMPORTANT:
 * Browsertrix records network traffic generated by the page. This behavior therefore
 * follows continuation URLs using the page's native fetch implementation. It does not
 * add API pages to the crawl queue as separate HTML pages.
 */

class ApiPaginationChainHunterBehavior {
  static id = "API Pagination Chain Hunter";
  static runInIframe = true;

  static init() {
    return {};
  }

  // Never become the active behavior. This preserves Browsertrix autoscroll and
  // existing site-specific behaviors. All work happens from hooks installed in onPageInit().
  static isMatch() {
    return false;
  }

  static onPageInit() {
    if (self.__bxApiChainHunterInstalled) return;
    self.__bxApiChainHunterInstalled = true;

    const CFG = {
      // Parsing / overhead controls
      maxJsonBytes: 8 * 1024 * 1024,
      maxHtmlBytes: 4 * 1024 * 1024,
      maxDepth: 40,
      maxNodes: 250000,
      maxUrlsPerJson: 5000,

      // Chain safety. A normal chain should terminate naturally; this is only a guard.
      maxChainPages: 10000,
      maxConcurrentChains: 2,

      // Politeness: generated continuation requests to the SAME API endpoint
      // are globally serialized and spaced by a fresh random 8-12 second delay.
      // Different endpoints may proceed independently.
      sameEndpointMinDelayMs: 8000,
      sameEndpointMaxDelayMs: 12000,

      // Media fetching safety
      maxMediaPerJson: 1000,
      mediaConcurrency: 6,
      fetchDocumentsToo: true,

      // Generic fallback is intentionally conservative on millions of pages.
      genericApiPathRx: /(?:\/api(?:\/|$)|\/graphql(?:\/|$)|\/ajax(?:\/|$)|\/json(?:\/|$)|\.json(?:$|[?#])|\/feed(?:\/|$)|\/search(?:\/|$)|\/query(?:\/|$)|\/list(?:\/|$)|\/items(?:\/|$)|\/posts(?:\/|$)|\/comments(?:\/|$)|\/media(?:\/|$))/i,
      jsonContentTypeRx: /(?:application|text)\/(?:[^;]+\+)?json\b|application\/graphql-response\+json\b/i,
      htmlContentTypeRx: /(?:text\/html|application\/xhtml\+xml)\b/i,

      mediaExtRx: /\.(?:jpe?g|png|gif|webp|avif|svg|ico|bmp|tiff?|mp4|m4v|webm|mov|m3u8|mpd|mp3|m4a|aac|ogg|oga|opus|wav|flac|pdf|epub|zip)(?:$|[?#])/i,
      mediaKeyRx: /(?:^|_)(?:url|uri|href|src|source|image|images|img|photo|thumbnail|thumb|cover|avatar|poster|video|audio|media|asset|attachment|attachments|download|file|files|document|documents|stream|playback|manifest|content_url|contenturl)(?:$|_)/i,

      // HTML pagination is intentionally strict. These selectors all imply a next-page URL.
      htmlNextSelectors: [
        'link[rel~="next"][href]',
        'a[rel~="next"][href]',
        'a.blog-pager-older-link[href]',
        '.blog-pager-older-link[href]',
        'a.w-pagination-next[href]',
        '.w-pagination-next[href]',
        'a.pagination-next[href]',
        'a.next-page[href]',
        'a.next_page[href]',
        'a[aria-label="Next"][href]',
        'a[aria-label="next"][href]',
        'a[aria-label="Næste"][href]',
        'a[aria-label="Ældre indlæg"][href]'
      ],

      debug: false,
    };

    const PLATFORM_RULES = [
      {
        id: "reddit",
        host: /(^|\.)reddit\.com$|(^|\.)redd\.it$/i,
        paths: ["data.after", "after"],
        requestParam: "after",
      },
      {
        id: "blogger",
        host: /(^|\.)blogger\.com$|(^|\.)blogspot\.[a-z.]+$|(^|\.)googleapis\.com$/i,
        paths: ["nextPageToken"],
        requestParam: "pageToken",
      },
      {
        id: "youtube",
        host: /(^|\.)youtube\.com$|(^|\.)googleapis\.com$|(^|\.)youtubei\.googleapis\.com$/i,
        paths: ["nextPageToken", "continuation", "nextContinuationData.continuation"],
        requestParam: "pageToken",
      },
      {
        id: "wix",
        host: /(^|\.)(?:wix\.com|wixapis\.com|wixsite\.com|wixstatic\.com)$/i,
        paths: [
          "pagingMetadata.cursors.next",
          "pagingMetadata.nextCursor",
          "pagination.nextCursor",
          "nextCursor",
        ],
        requestParam: "cursor",
      },
      {
        id: "squarespace",
        host: /(^|\.)squarespace\.com$|(^|\.)squarespace-cdn\.com$/i,
        paths: [
          "pagination.nextPageUrl",
          "pagination.nextPageCursor",
          "nextPageUrl",
          "nextPageCursor",
        ],
        requestParam: "cursor",
      },
      {
        id: "webflow",
        host: /(^|\.)webflow\.com$|(^|\.)webflow\.io$|(^|\.)webflowapi\.com$/i,
        paths: ["pagination.nextCursor", "nextCursor"],
        requestParam: "cursor",
      },
      {
        id: "shopify",
        host: /(^|\.)myshopify\.com$|(^|\.)shopify\.com$|(^|\.)shopifycdn\.com$/i,
        paths: ["pageInfo.endCursor", "endCursor"],
        requestParam: "after",
        requireFlag: ["pageInfo.hasNextPage", "hasNextPage"],
      },
      {
        id: "tiktok",
        host: /(^|\.)tiktok\.com$|(^|\.)tiktokcdn\.com$/i,
        paths: ["data.cursor", "cursor"],
        requestParam: "cursor",
        requireFlag: ["data.has_more", "has_more", "hasMore"],
      },
      {
        id: "disqus",
        host: /(^|\.)disqus\.com$|(^|\.)disquscdn\.com$/i,
        paths: ["cursor.next"],
        requestParam: "cursor",
        requireFlag: ["cursor.hasNext"],
      },
      {
        id: "pinterest",
        host: /(^|\.)pinterest\.[a-z.]+$|(^|\.)pinimg\.com$/i,
        paths: ["bookmark", "pagination.bookmark"],
        requestParam: "bookmark",
      },
      {
        id: "wordpress",
        host: /(^|\.)wordpress\.com$/i,
        paths: ["next", "links.next", "_links.next.href"],
        requestParam: "page",
      },
      {
        id: "tumblr",
        host: /(^|\.)tumblr\.com$/i,
        paths: ["_links.next.href", "links.next", "next", "next_cursor", "nextCursor"],
        requestParam: "offset",
      },
      {
        id: "medium",
        host: /(^|\.)medium\.com$/i,
        paths: ["next", "nextCursor", "paging.next", "paging.next.cursor"],
        requestParam: "cursor",
      },
      {
        id: "substack",
        host: /(^|\.)substack\.com$/i,
        paths: ["next", "nextCursor", "offset", "pagination.next"],
        requestParam: "offset",
      },
      {
        id: "issuu",
        host: /(^|\.)issuu\.com$|(^|\.)issuucloud\.com$/i,
        paths: ["next", "nextCursor", "cursor", "pagination.next", "pageInfo.endCursor"],
        requestParam: "cursor",
      },
      {
        id: "discourse",
        host: null,
        url: /(?:\/latest\.json|\/top\.json|\/search\.json|\/posts\.json|\/t\/[^/]+\/\d+\.json)/i,
        paths: ["topic_list.more_topics_url", "more_topics_url", "next"],
      },
      {
        id: "mastodon",
        host: null,
        url: /\/api\/v1\//i,
        paths: ["next", "next_url", "nextUrl", "max_id", "min_id"],
        requestParam: "max_id",
      },
      {
        id: "github",
        host: /(^|\.)github\.com$|(^|\.)githubusercontent\.com$/i,
        paths: ["next", "next_url", "nextUrl"],
        requestParam: "page",
      },
      {
        id: "gitlab",
        host: /(^|\.)gitlab\.com$/i,
        paths: ["next", "next_url", "nextUrl"],
        requestParam: "page",
      },
      {
        id: "facebook-meta",
        host: /(^|\.)(?:facebook\.com|fbcdn\.net|instagram\.com|cdninstagram\.com)$/i,
        paths: [
          "paging.next",
          "paging.cursors.after",
          "page_info.end_cursor",
          "pageInfo.endCursor",
        ],
        requestParam: "after",
      },
      {
        id: "x-twitter",
        host: /(^|\.)(?:x\.com|twitter\.com|twimg\.com)$/i,
        paths: ["next_token", "nextToken", "cursor", "next_cursor", "nextCursor"],
        requestParam: "cursor",
      },
      {
        id: "linkedin",
        host: /(^|\.)linkedin\.com$|(^|\.)licdn\.com$/i,
        paths: ["paging.next", "next", "nextCursor", "cursor"],
        requestParam: "start",
      },
      {
        id: "vimeo",
        host: /(^|\.)vimeo\.com$|(^|\.)vimeocdn\.com$/i,
        paths: ["paging.next", "next", "next_cursor", "nextCursor"],
        requestParam: "page",
      },
      {
        id: "flickr",
        host: /(^|\.)flickr\.com$|(^|\.)staticflickr\.com$/i,
        paths: ["photos.page", "page"],
        numbered: { page: ["photos.page", "page"], pages: ["photos.pages", "pages"] },
        requestParam: "page",
      },
    ];

    // Generic master signatures. Ordered strongest -> weaker contextual patterns.
    const GENERIC_SIGNATURES = [
      // Direct URL forms
      { paths: ["@odata.nextLink"], mode: "url", score: 100 },
      { paths: ["links.next", "_links.next.href", "pagination.nextPageUrl", "nextPageUrl", "next_page_url", "nextUrl", "next_url", "nextLink", "next_link"], mode: "auto", score: 100 },
      { paths: ["paging.next.link", "paging.next.url", "paging.next.href", "pagination.next.url", "pagination.next.href"], mode: "url", score: 100 },
      { paths: ["next"], mode: "auto", score: 80 },

      // Strong cursors / tokens
      { paths: ["response_metadata.next_cursor", "next_cursor", "nextCursor"], mode: "token", param: "cursor", score: 95 },
      { paths: ["next_page_token", "nextPageToken"], mode: "token", param: "pageToken", score: 95 },
      { paths: ["next_token", "nextToken"], mode: "token", param: "next_token", score: 95 },
      { paths: ["pagination.nextPageCursor", "nextPageCursor"], mode: "token", param: "cursor", score: 95 },
      { paths: ["pagingMetadata.cursors.next", "cursors.next"], mode: "token", param: "cursor", score: 98 },
      { paths: ["cursor.next"], mode: "token", param: "cursor", flags: ["cursor.hasNext"], score: 98 },
      { paths: ["pageInfo.endCursor"], mode: "token", param: "after", flags: ["pageInfo.hasNextPage"], score: 98 },
      { paths: ["page_info.end_cursor"], mode: "token", param: "after", flags: ["page_info.has_next_page"], score: 98 },
      { paths: ["paging.cursors.after", "paging.next.after"], mode: "token", param: "after", score: 95 },
      { paths: ["data.after"], mode: "token", param: "after", score: 95 },
      { paths: ["bookmark", "pagination.bookmark"], mode: "token", param: "bookmark", score: 90 },
      { paths: ["continue", "metadata.continue", "continuationToken", "continuation_token"], mode: "token", param: "continue", score: 90 },
      { paths: ["LastEvaluatedKey", "lastEvaluatedKey", "last_evaluated_key"], mode: "object-token", param: "ExclusiveStartKey", score: 90 },
      { paths: ["endCursor", "end_cursor"], mode: "token", param: "after", flags: ["hasNextPage", "has_next_page"], score: 85 },
      { paths: ["after"], mode: "token", param: "after", score: 55 },
      { paths: ["cursor"], mode: "token", param: "cursor", flags: ["has_more", "hasMore", "hasNext", "has_next"], score: 70 },

      // Discourse and similar direct "more" URL
      { paths: ["topic_list.more_topics_url", "more_topics_url", "moreTopicsUrl"], mode: "url", score: 98 },
    ];

    const state = {
      activeChains: 0,
      seenChainRequests: new Set(),
      fetchedMedia: new Set(),
      endpointQueues: new Map(),
      lastEndpointCallAt: new Map(),
      nativeFetch: self.fetch ? self.fetch.bind(self) : null,
      NativeXHR: self.XMLHttpRequest,
    };

    function log(...args) {
      if (CFG.debug) console.debug("[API Chain Hunter]", ...args);
    }

    function safeUrl(value, base) {
      if (typeof value !== "string" || !value) return null;
      try {
        if (/^(?:data|blob|javascript|mailto|tel):/i.test(value)) return null;
        return new URL(value, base).href;
      } catch (_) {
        return null;
      }
    }

    function getByPath(obj, path) {
      if (!obj || !path) return undefined;
      const parts = path.split(".");
      let cur = obj;
      for (const part of parts) {
        if (cur == null || typeof cur !== "object" || !(part in cur)) return undefined;
        cur = cur[part];
      }
      return cur;
    }

    function findByKeyDeep(root, wantedKeys) {
      const wanted = new Set(wantedKeys.map((x) => x.toLowerCase()));
      const out = [];
      const stack = [{ value: root, path: "", depth: 0 }];
      let nodes = 0;
      while (stack.length && nodes++ < CFG.maxNodes) {
        const { value, path, depth } = stack.pop();
        if (!value || typeof value !== "object" || depth > CFG.maxDepth) continue;
        if (Array.isArray(value)) {
          for (let i = Math.min(value.length, 2000) - 1; i >= 0; i--) {
            const v = value[i];
            if (v && typeof v === "object") stack.push({ value: v, path: path + "[" + i + "]", depth: depth + 1 });
          }
          continue;
        }
        for (const [k, v] of Object.entries(value)) {
          const p = path ? path + "." + k : k;
          if (wanted.has(k.toLowerCase())) out.push({ path: p, value: v });
          if (v && typeof v === "object") stack.push({ value: v, path: p, depth: depth + 1 });
        }
      }
      return out;
    }

    function classify(url) {
      let u;
      try { u = new URL(url, location.href); } catch (_) { return null; }
      for (const r of PLATFORM_RULES) {
        if (r.host && r.host.test(u.hostname)) return r;
        if (r.url && r.url.test(u.href)) return r;
      }
      if (CFG.genericApiPathRx.test(u.pathname + u.search)) return { id: "generic-api", paths: [] };
      return null;
    }

    function isJsonCandidate(url, headers, platform) {
      const ct = headers && typeof headers.get === "function" ? (headers.get("content-type") || "") : "";
      if (CFG.jsonContentTypeRx.test(ct)) return true;
      // Some APIs mislabel JSON, so URL structure may still qualify it. Platform host
      // alone is deliberately NOT sufficient; that would make us inspect images/scripts
      // on large hosts such as reddit, Wix, TikTok, etc.
      return CFG.genericApiPathRx.test(url);
    }

    function findHeaderContinuation(headers, requestUrl) {
      if (!headers || typeof headers.get !== "function") return null;

      // RFC 8288 style Link header, used by GitHub, Mastodon and many REST APIs.
      const link = headers.get("link") || "";
      if (link) {
        for (const part of link.split(",")) {
          if (!/;\s*rel\s*=\s*["']?next["']?/i.test(part)) continue;
          const m = part.match(/<([^>]+)>/);
          if (m && m[1]) return { platform: "http-link", path: "Link rel=next", value: m[1], mode: "url", score: 100 };
        }
      }

      // GitLab and a number of APIs expose the next page directly.
      const xNextPage = headers.get("x-next-page");
      if (xNextPage) return { platform: "http-x-next-page", path: "X-Next-Page", value: xNextPage, mode: "token", param: "page", score: 98 };

      // WordPress REST API.
      const totalPages = Number(headers.get("x-wp-totalpages"));
      if (Number.isFinite(totalPages) && totalPages > 1) {
        try {
          const u = new URL(requestUrl, location.href);
          const current = Number(u.searchParams.get("page") || "1");
          if (current < totalPages) return { platform: "wordpress", path: "X-WP-TotalPages", value: current + 1, mode: "token", param: "page", score: 100 };
        } catch (_) {}
      }
      return null;
    }

    function flagAllows(json, flags) {
      if (!flags || !flags.length) return true;
      for (const p of flags) {
        const v = getByPath(json, p);
        if (v === true) return true;
        if (v === false) continue;
      }
      // If the expected flag is absent, do not veto a strong cursor signature.
      return flags.every((p) => getByPath(json, p) === undefined);
    }

    function looksLikeAbsoluteOrRelativeUrl(v) {
      return typeof v === "string" && (/^https?:\/\//i.test(v) || /^\//.test(v) || /^\.\.?\//.test(v));
    }

    function findContinuation(json, requestUrl, platform) {
      // 1) Platform-specific exact paths first.
      if (platform && Array.isArray(platform.paths)) {
        if (!platform.requireFlag || flagAllows(json, platform.requireFlag)) {
          for (const path of platform.paths) {
            const v = getByPath(json, path);
            if (v !== undefined && v !== null && v !== "" && v !== false) {
              if (platform.numbered) break;
              return {
                platform: platform.id,
                path,
                value: v,
                mode: looksLikeAbsoluteOrRelativeUrl(v) ? "url" : "token",
                param: platform.requestParam,
                score: 100,
              };
            }
          }
        }
        if (platform.numbered) {
          const page = firstDefined(json, platform.numbered.page || []);
          const pages = firstDefined(json, platform.numbered.pages || []);
          if (Number.isFinite(Number(page)) && Number.isFinite(Number(pages)) && Number(page) < Number(pages)) {
            return { platform: platform.id, path: "numbered", value: Number(page) + 1, mode: "token", param: platform.requestParam || "page", score: 95 };
          }
        }
      }

      // 2) Exact generic paths.
      for (const sig of GENERIC_SIGNATURES) {
        if (!flagAllows(json, sig.flags)) continue;
        for (const path of sig.paths) {
          const v = getByPath(json, path);
          if (v === undefined || v === null || v === "" || v === false) continue;
          let mode = sig.mode;
          if (mode === "auto") mode = looksLikeAbsoluteOrRelativeUrl(v) ? "url" : "token";
          return { platform: platform ? platform.id : "generic", path, value: v, mode, param: sig.param, score: sig.score };
        }
      }

      // 3) Context-aware deep fallback, only on API-looking responses.
      const deep = findByKeyDeep(json, [
        "nextPageToken", "next_page_token", "nextCursor", "next_cursor",
        "nextToken", "next_token", "endCursor", "end_cursor", "bookmark",
        "continuationToken", "continuation_token", "more_topics_url",
      ]);
      if (deep.length) {
        const hit = deep[0];
        const key = hit.path.split(".").pop().replace(/\[.*$/, "");
        const paramMap = {
          nextPageToken: "pageToken", next_page_token: "page_token",
          nextCursor: "cursor", next_cursor: "cursor",
          nextToken: "next_token", next_token: "next_token",
          endCursor: "after", end_cursor: "after", bookmark: "bookmark",
          continuationToken: "continuation", continuation_token: "continuation",
          more_topics_url: null,
        };
        return {
          platform: platform ? platform.id : "generic",
          path: hit.path,
          value: hit.value,
          mode: looksLikeAbsoluteOrRelativeUrl(hit.value) ? "url" : "token",
          param: paramMap[key],
          score: 75,
        };
      }

      // 4) Offset/page tuple inference.
      const page = firstDefined(json, ["page", "currentPage", "current_page"]);
      const pages = firstDefined(json, ["pages", "totalPages", "total_pages", "pageCount", "page_count", "numPages", "num_pages"]);
      if (Number.isFinite(Number(page)) && Number.isFinite(Number(pages)) && Number(page) < Number(pages)) {
        return { platform: "generic-numbered", path: "page/pages", value: Number(page) + 1, mode: "token", param: "page", score: 80 };
      }
      const offset = firstDefined(json, ["offset", "pagination.offset", "paging.offset", "pagingMetadata.offset"]);
      const limit = firstDefined(json, ["limit", "pagination.limit", "paging.limit", "pagingMetadata.limit", "pageSize", "page_size", "perPage", "per_page"]);
      const total = firstDefined(json, ["total", "totalCount", "total_count", "pagination.total", "paging.total"]);
      if ([offset, limit, total].every((x) => Number.isFinite(Number(x))) && Number(offset) + Number(limit) < Number(total)) {
        return { platform: "generic-offset", path: "offset/limit/total", value: Number(offset) + Number(limit), mode: "token", param: "offset", score: 80 };
      }

      return null;
    }

    function firstDefined(obj, paths) {
      for (const p of paths) {
        const v = getByPath(obj, p);
        if (v !== undefined && v !== null) return v;
      }
      return undefined;
    }

    function inferParamFromOriginal(url, cont) {
      let u;
      try { u = new URL(url, location.href); } catch (_) { return cont.param || null; }
      const keys = [...u.searchParams.keys()];
      const candidates = [
        cont.param,
        "after", "cursor", "pageToken", "page_token", "next_token", "nextToken",
        "bookmark", "continuation", "continue", "page", "offset", "start", "max_id",
      ].filter(Boolean);
      for (const c of candidates) if (keys.includes(c)) return c;
      return cont.param || candidates[0] || null;
    }

    function buildNextUrl(requestUrl, cont) {
      if (cont.mode === "url") return safeUrl(cont.value, requestUrl);
      if (cont.mode === "object-token") return null; // needs request-body/API-specific handling
      if (["string", "number"].includes(typeof cont.value)) {
        try {
          const u = new URL(requestUrl, location.href);
          const param = inferParamFromOriginal(u.href, cont);
          if (!param) return null;
          u.searchParams.set(param, String(cont.value));
          return u.href;
        } catch (_) {
          return null;
        }
      }
      return null;
    }

    function cloneHeaders(headers) {
      try {
        const out = {};
        new Headers(headers || {}).forEach((v, k) => { out[k] = v; });
        return out;
      } catch (_) {
        return {};
      }
    }

    function snapshotRequest(input, init) {
      try {
        if (input instanceof Request) {
          return {
            url: input.url,
            method: (init && init.method) || input.method || "GET",
            headers: cloneHeaders((init && init.headers) || input.headers),
            body: init && "body" in init ? init.body : null,
            credentials: (init && init.credentials) || input.credentials || "same-origin",
            mode: (init && init.mode) || input.mode,
            cache: (init && init.cache) || input.cache,
            referrer: input.referrer,
          };
        }
        return {
          url: new URL(String(input), location.href).href,
          method: (init && init.method) || "GET",
          headers: cloneHeaders(init && init.headers),
          body: init && "body" in init ? init.body : null,
          credentials: (init && init.credentials) || "same-origin",
          mode: init && init.mode,
          cache: init && init.cache,
        };
      } catch (_) {
        return null;
      }
    }

    function maybeModifyJsonBody(req, cont) {
      if (!req || !req.body || typeof req.body !== "string") return null;
      let body;
      try { body = JSON.parse(req.body); } catch (_) { return null; }

      const token = cont.value;
      let changed = false;

      // GraphQL Relay: variables.after / cursor-like variables.
      if (body && typeof body === "object") {
        if (body.variables && typeof body.variables === "object") {
          const vars = body.variables;
          const preferred = [cont.param, "after", "cursor", "pageToken", "page_token", "offset"].filter(Boolean);
          for (const p of preferred) {
            if (p in vars || p === cont.param) {
              vars[p] = token;
              changed = true;
              break;
            }
          }
        }

        // Wix-style REST query body.
        if (!changed && body.query && typeof body.query === "object") {
          if (getByPath(body, "query.cursorPaging") !== undefined || cont.platform === "wix") {
            body.query.cursorPaging = { cursor: token };
            if (body.query.paging) delete body.query.paging;
            changed = true;
          } else if (body.query.paging && cont.param === "offset") {
            body.query.paging.offset = token;
            changed = true;
          }
        }

        // TikTok-style POST body.
        if (!changed && cont.param && (cont.param in body || cont.platform === "tiktok")) {
          body[cont.param] = token;
          changed = true;
        }
      }

      return changed ? JSON.stringify(body) : null;
    }

    function nextRequestFrom(req, cont) {
      if (!req) return null;
      const method = String(req.method || "GET").toUpperCase();
      if (method === "GET" || method === "HEAD") {
        const url = buildNextUrl(req.url, cont);
        if (!url) return null;
        return { ...req, url, method: "GET", body: null };
      }

      if (cont.mode === "url") {
        const url = safeUrl(cont.value, req.url);
        if (!url) return null;
        // Preserve POST only if URL points to same API endpoint style; otherwise GET is safer.
        return { ...req, url };
      }

      const body = maybeModifyJsonBody(req, cont);
      if (!body) return null;
      return { ...req, body };
    }

    function requestFingerprint(req) {
      const body = typeof req.body === "string" ? req.body.slice(0, 4096) : "";
      return [req.method, req.url, body].join("\n");
    }

    // A logical endpoint deliberately ignores query parameters, since those are
    // normally where page/cursor/offset values change. Method is included so a
    // GET collection and POST/GraphQL endpoint do not accidentally share a bucket.
    function endpointKey(reqOrUrl, method = "GET") {
      try {
        const rawUrl = typeof reqOrUrl === "string" ? reqOrUrl : reqOrUrl.url;
        const rawMethod = typeof reqOrUrl === "string" ? method : (reqOrUrl.method || method);
        const u = new URL(rawUrl, location.href);
        const path = u.pathname.replace(/\/+$/, "") || "/";
        return String(rawMethod || "GET").toUpperCase() + " " + u.origin + path;
      } catch (_) {
        return String(method || "GET").toUpperCase() + " " + String(reqOrUrl && reqOrUrl.url || reqOrUrl || "");
      }
    }

    function randomSameEndpointDelayMs() {
      const min = Math.max(0, Number(CFG.sameEndpointMinDelayMs) || 0);
      const max = Math.max(min, Number(CFG.sameEndpointMaxDelayMs) || min);
      return Math.floor(min + Math.random() * (max - min + 1));
    }

    function sleep(ms) {
      return ms > 0 ? new Promise((resolve) => setTimeout(resolve, ms)) : Promise.resolve();
    }

    // Record a page-originated relevant API call. Because detection happens after
    // its response arrives, using Date.now() is intentionally conservative: the
    // first generated continuation waits 8-12s after we have confirmed the response.
    function noteObservedApiRequest(req) {
      if (!req || !req.url) return;
      state.lastEndpointCallAt.set(endpointKey(req), Date.now());
    }

    async function fetchRequest(req) {
      if (!state.nativeFetch) return null;
      const init = {
        method: req.method || "GET",
        headers: req.headers || {},
        credentials: req.credentials || "same-origin",
      };
      if (req.body != null && !/^(?:GET|HEAD)$/i.test(init.method)) init.body = req.body;
      // Reuse browser context/cookies. Avoid forcing a mode if it was not explicitly known.
      if (req.mode && req.mode !== "navigate") init.mode = req.mode;
      try {
        return await state.nativeFetch(req.url, init);
      } catch (e) {
        log("chain fetch failed", req.url, e && e.message);
        return null;
      }
    }

    async function politeFetchRequest(req) {
      const key = endpointKey(req);
      const previous = state.endpointQueues.get(key) || Promise.resolve();

      const task = previous.catch(() => {}).then(async () => {
        const targetGap = randomSameEndpointDelayMs();
        const lastAt = state.lastEndpointCallAt.get(key) || 0;
        const elapsed = Date.now() - lastAt;
        const remaining = Math.max(0, targetGap - elapsed);
        if (remaining > 0) {
          log("polite wait", key, remaining + "ms");
          await sleep(remaining);
        }

        // Timestamp immediately before sending. This guarantees the spacing is
        // between request starts, while the per-endpoint queue prevents races.
        state.lastEndpointCallAt.set(key, Date.now());
        return await fetchRequest(req);
      });

      state.endpointQueues.set(key, task);
      try {
        return await task;
      } finally {
        if (state.endpointQueues.get(key) === task) state.endpointQueues.delete(key);
      }
    }

    function likelyMediaByKey(key, url) {
      return CFG.mediaKeyRx.test(key || "") || CFG.mediaExtRx.test(url || "");
    }

    function extractUrls(json, baseUrl) {
      const urls = [];
      const stack = [{ value: json, key: "", depth: 0 }];
      let nodes = 0;
      while (stack.length && urls.length < CFG.maxUrlsPerJson && nodes++ < CFG.maxNodes) {
        const { value, key, depth } = stack.pop();
        if (depth > CFG.maxDepth) continue;
        if (typeof value === "string") {
          const u = safeUrl(value, baseUrl);
          if (u && /^https?:/i.test(u)) urls.push({ url: u, key, media: likelyMediaByKey(key, u) });
          continue;
        }
        if (!value || typeof value !== "object") continue;
        if (Array.isArray(value)) {
          for (let i = Math.min(value.length, 5000) - 1; i >= 0; i--) stack.push({ value: value[i], key, depth: depth + 1 });
        } else {
          for (const [k, v] of Object.entries(value)) stack.push({ value: v, key: k, depth: depth + 1 });
        }
      }
      return urls;
    }

    async function pool(items, concurrency, fn) {
      let index = 0;
      const workers = new Array(Math.min(concurrency, items.length)).fill(0).map(async () => {
        while (index < items.length) {
          const item = items[index++];
          try { await fn(item); } catch (_) {}
        }
      });
      await Promise.all(workers);
    }

    async function fetchMediaFromJson(json, baseUrl) {
      if (!state.nativeFetch) return;
      const all = extractUrls(json, baseUrl);
      const chosen = [];
      for (const item of all) {
        if (!item.media && !CFG.fetchDocumentsToo) continue;
        if (!item.media && !CFG.mediaExtRx.test(item.url)) continue;
        if (state.fetchedMedia.has(item.url)) continue;
        state.fetchedMedia.add(item.url);
        chosen.push(item.url);
        if (chosen.length >= CFG.maxMediaPerJson) break;
      }
      await pool(chosen, CFG.mediaConcurrency, async (url) => {
        try {
          // no-cors still causes the network resource to be requested/recorded while
          // avoiding most cross-origin JS access restrictions.
          await state.nativeFetch(url, { method: "GET", mode: "no-cors", credentials: "include", cache: "default" });
        } catch (_) {
          // The recorder may still have observed a response even when JS sees CORS/network failure.
        }
      });
    }

    async function parseJsonResponse(resp) {
      try {
        const len = Number(resp.headers && resp.headers.get && resp.headers.get("content-length"));
        if (Number.isFinite(len) && len > CFG.maxJsonBytes) return null;
        const txt = await resp.text();
        if (!txt || txt.length > CFG.maxJsonBytes) return null;
        const first = txt.trimStart()[0];
        if (first !== "{" && first !== "[") return null;
        return JSON.parse(txt);
      } catch (_) {
        return null;
      }
    }

    async function parseHtmlResponse(resp) {
      try {
        const len = Number(resp.headers && resp.headers.get && resp.headers.get("content-length"));
        if (Number.isFinite(len) && len > CFG.maxHtmlBytes) return null;
        const txt = await resp.text();
        if (!txt || txt.length > CFG.maxHtmlBytes) return null;
        // Cheap prefilter before DOMParser. Most fetched HTML has none of these tokens.
        if (!/(?:rel\s*=\s*["']?next|blog-pager-older-link|w-pagination-next|pagination-next|next-page|next_page|aria-label\s*=\s*["'](?:Next|next|Næste|Ældre indlæg))/i.test(txt)) return null;
        return txt;
      } catch (_) {
        return null;
      }
    }

    function findHtmlContinuation(html, requestUrl) {
      if (!html || typeof DOMParser === "undefined") return null;
      let doc;
      try { doc = new DOMParser().parseFromString(html, "text/html"); } catch (_) { return null; }
      if (!doc) return null;

      for (const selector of CFG.htmlNextSelectors) {
        let el = null;
        try { el = doc.querySelector(selector); } catch (_) {}
        if (!el) continue;
        const raw = el.getAttribute("href");
        const href = safeUrl(raw, requestUrl);
        if (!href || href === requestUrl) continue;
        return {
          platform: "html-pagination",
          path: selector,
          value: href,
          mode: "url",
          score: selector.includes('rel~=') ? 100 : 95,
        };
      }
      return null;
    }

    async function followHtmlChain(initialReq, initialHtml, initialHeaderCont = null) {
      if (state.activeChains >= CFG.maxConcurrentChains) return;
      state.activeChains++;
      try {
        let req = initialReq;
        let html = initialHtml;
        let headerCont = initialHeaderCont;
        let count = 0;

        while ((html || headerCont) && count++ < CFG.maxChainPages) {
          const cont = headerCont || findHtmlContinuation(html, req.url);
          headerCont = null;
          if (!cont) break;
          const nextReq = { ...req, url: cont.value, method: "GET", body: null };
          const fp = requestFingerprint(nextReq);
          if (state.seenChainRequests.has(fp)) break;
          state.seenChainRequests.add(fp);

          const resp = await politeFetchRequest(nextReq);
          if (!resp || !resp.ok) break;
          const ct = resp.headers.get("content-type") || "";
          if (!CFG.htmlContentTypeRx.test(ct)) break;
          const nextHeaderCont = findHeaderContinuation(resp.headers, nextReq.url);
          const nextHtml = await parseHtmlResponse(resp.clone());
          if (!nextHtml && !nextHeaderCont) break;

          req = nextReq;
          html = nextHtml || "";
          headerCont = nextHeaderCont;
        }

        if (count >= CFG.maxChainPages) log("maxChainPages reached (HTML)", initialReq.url);
      } finally {
        state.activeChains--;
      }
    }

    async function followChain(initialReq, initialJson, initialPlatform, initialHeaderCont = null) {
      if (state.activeChains >= CFG.maxConcurrentChains) return;
      state.activeChains++;
      try {
        let req = initialReq;
        let json = initialJson;
        let platform = initialPlatform;
        let headerCont = initialHeaderCont;
        let count = 0;

        while (json && count++ < CFG.maxChainPages) {
          await fetchMediaFromJson(json, req.url);

          const cont = headerCont || findContinuation(json, req.url, platform);
          headerCont = null;
          if (!cont) break;
          const nextReq = nextRequestFrom(req, cont);
          if (!nextReq) {
            log("continuation found but request could not be constructed", cont, req.url);
            break;
          }
          const fp = requestFingerprint(nextReq);
          if (state.seenChainRequests.has(fp)) break;
          state.seenChainRequests.add(fp);

          const resp = await politeFetchRequest(nextReq);
          if (!resp || !resp.ok) break;
          const ct = resp.headers.get("content-type") || "";
          if (!CFG.jsonContentTypeRx.test(ct) && !CFG.genericApiPathRx.test(nextReq.url)) break;
          const nextJson = await parseJsonResponse(resp.clone());
          if (!nextJson) break;

          req = nextReq;
          json = nextJson;
          platform = classify(req.url) || platform;
          headerCont = findHeaderContinuation(resp.headers, req.url);
        }

        if (count >= CFG.maxChainPages) log("maxChainPages reached", initialReq.url);
      } finally {
        state.activeChains--;
      }
    }

    async function inspectFetchResponse(req, resp) {
      if (!req || !resp) return;
      const platform = classify(req.url);
      const ct = resp.headers.get("content-type") || "";
      const len = Number(resp.headers.get("content-length"));
      const headerCont = findHeaderContinuation(resp.headers, req.url);

      // JSON path: explicit HTML content-type always wins over URL heuristics.
      // This matters for Blogger/Webflow-style endpoints whose URL may contain
      // words like /posts while the payload is an HTML fragment.
      const explicitHtml = CFG.htmlContentTypeRx.test(ct);
      if (!explicitHtml && isJsonCandidate(req.url, resp.headers, platform)) {
        if (!CFG.jsonContentTypeRx.test(ct) && !CFG.genericApiPathRx.test(req.url)) return;
        if (Number.isFinite(len) && len > CFG.maxJsonBytes) return;

        noteObservedApiRequest(req);
        const json = await parseJsonResponse(resp.clone());
        if (!json) return;

        const cont = headerCont || findContinuation(json, req.url, platform);
        // Fetch media from any relevant JSON response, even if it is a one-page list.
        if (platform || cont) void fetchMediaFromJson(json, req.url);
        if (!cont) return;

        const fp = requestFingerprint(req);
        if (state.seenChainRequests.has(fp)) return;
        state.seenChainRequests.add(fp);
        void followChain(req, json, platform, headerCont);
        return;
      }

      // HTML returned by fetch/XHR: only inspect actual HTML and only parse it if a
      // very cheap string prefilter finds a strong next-page marker.
      if (!CFG.htmlContentTypeRx.test(ct)) return;
      if (Number.isFinite(len) && len > CFG.maxHtmlBytes) return;
      const html = await parseHtmlResponse(resp.clone());
      if (!html && !headerCont) return;

      const cont = headerCont || findHtmlContinuation(html, req.url);
      if (!cont) return;
      noteObservedApiRequest(req);

      const fp = requestFingerprint(req);
      if (state.seenChainRequests.has(fp)) return;
      state.seenChainRequests.add(fp);
      void followHtmlChain(req, html || "", headerCont);
    }

    // ----- fetch() hook -----
    if (state.nativeFetch) {
      self.fetch = async function(input, init) {
        const req = snapshotRequest(input, init);
        const resp = await state.nativeFetch(input, init);
        // Do not delay the page: inspect asynchronously on a clone.
        if (req && resp) Promise.resolve().then(() => inspectFetchResponse(req, resp.clone())).catch(() => {});
        return resp;
      };
    }

    // ----- XMLHttpRequest hook -----
    if (state.NativeXHR && state.NativeXHR.prototype) {
      const proto = state.NativeXHR.prototype;
      const origOpen = proto.open;
      const origSend = proto.send;
      const origSetHeader = proto.setRequestHeader;

      proto.open = function(method, url, async, user, password) {
        try {
          this.__bxChainReq = {
            url: new URL(String(url), location.href).href,
            method: String(method || "GET").toUpperCase(),
            headers: {},
            body: null,
            credentials: "include",
          };
        } catch (_) {}
        return origOpen.apply(this, arguments);
      };

      proto.setRequestHeader = function(k, v) {
        try {
          if (this.__bxChainReq) this.__bxChainReq.headers[String(k)] = String(v);
        } catch (_) {}
        return origSetHeader.apply(this, arguments);
      };

      proto.send = function(body) {
        try {
          if (this.__bxChainReq) this.__bxChainReq.body = typeof body === "string" ? body : null;
          this.addEventListener("loadend", () => {
            const req = this.__bxChainReq;
            if (!req || this.status < 200 || this.status >= 300) return;
            const platform = classify(req.url);
            const ct = this.getResponseHeader("content-type") || "";

            // Minimal Headers-like object so XHR responses can use the same
            // Link/X-Next-Page/X-WP-TotalPages continuation logic as fetch().
            const xhrHeaders = {
              get: (name) => {
                try { return this.getResponseHeader(name); } catch (_) { return null; }
              }
            };
            const headerCont = findHeaderContinuation(xhrHeaders, req.url);

            let text = null;
            try {
              if (this.responseType === "json" && this.response && typeof this.response === "object") {
                noteObservedApiRequest(req);
                const json = this.response;
                const cont = headerCont || findContinuation(json, req.url, platform);
                if (platform || cont) void fetchMediaFromJson(json, req.url);
                if (cont) void followChain(req, json, platform, headerCont);
                return;
              }
              if (this.responseType === "" || this.responseType === "text") text = this.responseText;
            } catch (_) { return; }
            if (!text) return;

            // JSON XHR path. Explicit HTML content-type takes precedence over
            // an API-looking URL such as /posts or /search.
            const explicitHtml = CFG.htmlContentTypeRx.test(ct);
            if (!explicitHtml && (CFG.jsonContentTypeRx.test(ct) || CFG.genericApiPathRx.test(req.url))) {
              if (text.length > CFG.maxJsonBytes) return;
              const first = text.trimStart()[0];
              if (first !== "{" && first !== "[") return;
              try {
                const json = JSON.parse(text);
                const cont = headerCont || findContinuation(json, req.url, platform);
                if (platform || cont) void fetchMediaFromJson(json, req.url);
                if (cont) {
                  noteObservedApiRequest(req);
                  void followChain(req, json, platform, headerCont);
                }
              } catch (_) {}
              return;
            }

            // HTML fragments/pages loaded through XHR. Use the same cheap token
            // prefilter before DOMParser to keep the common case inexpensive.
            if (CFG.htmlContentTypeRx.test(ct)) {
              if (text.length > CFG.maxHtmlBytes) return;
              if (!headerCont && !/(?:rel\s*=\s*["']?next|blog-pager-older-link|w-pagination-next|pagination-next|next-page|next_page|aria-label\s*=\s*["'](?:Next|next|Næste|Ældre indlæg))/i.test(text)) return;
              const cont = headerCont || findHtmlContinuation(text, req.url);
              if (!cont) return;
              noteObservedApiRequest(req);
              void followHtmlChain(req, text, headerCont);
            }
          }, { once: true });
        } catch (_) {}
        return origSend.apply(this, arguments);
      };
    }
  }

  // Required by the custom behavior interface, but deliberately unused.
  async *run(ctx) {
    yield ctx.Lib.getState(ctx, "API Pagination Chain Hunter hook installed");
  }
}
