// YT-DLP Universal Media Behavior v0.2.0
// Generated by build_ytdlp_browsertrix_behavior.py
// yt-dlp version: standalone-v0.2.0
// Extractors indexed: 3
// Host suffixes indexed: 6
//
// Design:
//   1) Cheap yt-dlp-derived URL/hostname suitability check.
//   2) Initial direct-media/provider scan.
//   3) If useful media is not yet exposed, click at most ONE visible play button.
//   4) Wait for DOM/network/player initialization.
//   5) Run only relevant provider handlers + generic media extraction.
//   6) Send direct files to Browsertrix doExternalFetch().
//
// This is yt-dlp-inspired, not a Python-to-JavaScript translation of every extractor.
// Site-specific yt-dlp API/signature/DRM logic cannot be executed directly in an in-page behavior.

class YtDlpUniversalMediaBehavior {
  static id = "ytdlp-universal-media";
  static version = "0.2.0";
  static runInIframes = true;

  static extractorRegistry = [{"n":"Youtube","h":["youtube.com","youtu.be","youtube-nocookie.com"],"r":[],"u":1},{"n":"Vimeo","h":["vimeo.com","player.vimeo.com"],"r":[],"u":1},{"n":"Kaltura","h":["kaltura.com"],"r":[],"u":1}];
  static hostIndex = {"youtube.com":[0],"youtu.be":[0],"youtube-nocookie.com":[0],"vimeo.com":[1],"player.vimeo.com":[1],"kaltura.com":[2]};
  static unindexedExtractorIds = [];
  static regexCache = new Map();

  static init() {
    return {
      state: {
        matchedExtractors: [],
        playButtonFound: false,
        playButtonClicked: false,
        playerChangeDetected: false,
        providerHints: [],
        youtubeHandlerRuns: 0,
        youtubeCipherFormatsSkipped: 0,
        vimeoHandlerRuns: 0,
        vimeoConfigsFound: 0,
        directFilesFound: 0,
        manifestsFound: 0,
        iframeEmbedsFound: 0,
        fetched: 0,
      },
      opts: {},
    };
  }

  static hostCandidates(host) {
    host = String(host || "").toLowerCase().replace(/^www\./, "");
    const labels = host.split(".").filter(Boolean);
    const out = [];
    for (let i = 0; i < labels.length - 1; i++) {
      out.push(labels.slice(i).join("."));
    }
    return out;
  }

  static candidateExtractorIds(host) {
    const ids = new Set();
    for (const suffix of this.hostCandidates(host)) {
      const found = this.hostIndex[suffix];
      if (found) {
        for (const id of found) ids.add(id);
      }
    }
    for (const id of this.unindexedExtractorIds) ids.add(id);
    return [...ids];
  }

  static testExtractor(recId, url) {
    const rec = this.extractorRegistry[recId];
    if (!rec) return false;
    if (!rec.r || !rec.r.length) return true; // Host-index fallback for unconvertible regex.

    let compiled = this.regexCache.get(recId);
    if (!compiled) {
      compiled = [];
      for (const spec of rec.r) {
        try {
          compiled.push(new RegExp(spec.p, spec.f || ""));
        } catch (_) {}
      }
      this.regexCache.set(recId, compiled);
    }

    // If every transformed regex failed to compile, retain the conservative host-level match.
    if (!compiled.length) return true;
    const matched = compiled.some((re) => {
      try {
        re.lastIndex = 0;
        return re.test(url);
      } catch (_) {
        return false;
      }
    });
    // If some Python patterns could not be translated to JavaScript, preserve a
    // conservative host-level match rather than silently excluding that extractor.
    return matched || Number(rec.u || 0) > 0;
  }

  static matchedExtractorIds(url = location.href) {
    let host = "";
    try {
      host = new URL(url, location.href).hostname;
    } catch (_) {
      host = location.hostname;
    }
    return this.candidateExtractorIds(host).filter((id) => this.testExtractor(id, url));
  }

  static cheapMediaHint() {
    try {
      if (document.querySelector(
        "video, audio, source[src], iframe[src*='youtube'], iframe[src*='youtu.be'], " +
        "iframe[src*='vimeo'], iframe[src*='kaltura'], iframe[src*='brightcove'], " +
        "iframe[src*='jwplayer'], iframe[src*='jwplatform'], iframe[src*='mux.com'], " +
        "iframe[src*='videodelivery.net'], button.tv-hero-play-button, " +
        ".vjs-big-play-button, .jw-icon-playback, .ytp-large-play-button, " +
        ".plyr__control[data-plyr='play']"
      )) return true;

      const html = document.documentElement && document.documentElement.innerHTML;
      if (html && /(?:\.m3u8|\.mpd|\.mp4|kaltura|jwplayer|brightcove|youtube|vimeo|stream\.mux\.com|videodelivery\.net)/i.test(html)) {
        return true;
      }
    } catch (_) {}
    return false;
  }

  static isMatch() {
    if (!/^https?:$/i.test(location.protocol)) return false;
    if (this.matchedExtractorIds(location.href).length) return true;

    // yt-dlp itself notes that embeds/generic extraction can support sites not present in its
    // supported-site list, so retain a strong-media-hint fallback without matching every page.
    return this.cheapMediaHint();
  }

  async *run(ctx) {
    const {
      getState,
      sleep,
      scrollAndClick,
      waitForNetworkIdle,
      doExternalFetch,
      addLink,
    } = ctx.Lib;

    const matchedIds = YtDlpUniversalMediaBehavior.matchedExtractorIds(location.href);
    const matched = matchedIds.map((id) => YtDlpUniversalMediaBehavior.extractorRegistry[id]).filter(Boolean);
    ctx.state.matchedExtractors = matched.map((x) => x.n);

    yield getState(
      ctx,
      "YT-DLP Universal: matched extractors: " +
        (ctx.state.matchedExtractors.length ? ctx.state.matchedExtractors.join(", ") : "embed/generic-media fallback")
    );

    const media = new Map();
    const iframeEmbeds = new Map();
    const providerHints = new Set();
    const seenKalturaEntries = new Set();
    const seenVimeoConfigUrls = new Set();
    const seenVimeoConfigObjects = new WeakSet();
    const seenYouTubePlayerResponses = new WeakSet();

    function safeUrl(raw, base = document.baseURI) {
      if (typeof raw !== "string") return null;
      let value = raw.trim()
        .replace(/\\u0026/gi, "&")
        .replace(/\\u002F/gi, "/")
        .replace(/\\\//g, "/")
        .replace(/&amp;/gi, "&");
      if (!value || /^(?:blob:|data:|javascript:)/i.test(value)) return null;
      if (value.startsWith("//")) value = location.protocol + value;
      try {
        return new URL(value, base).href;
      } catch (_) {
        return null;
      }
    }

    function classifyMedia(url, mime = "") {
      const u = String(url || "").toLowerCase();
      const m = String(mime || "").toLowerCase();
      if (/\.(?:mp4|m4v)(?:$|[?#])/.test(u) || m.includes("video/mp4")) return "file";
      if (/\.webm(?:$|[?#])/.test(u) || m.includes("video/webm")) return "file";
      if (/\.(?:mp3|m4a|aac|ogg|opus)(?:$|[?#])/.test(u) || /^audio\//.test(m)) return "file";
      if (/\.m3u8(?:$|[?#])/.test(u) || m.includes("mpegurl")) return "hls";
      if (/\.mpd(?:$|[?#])/.test(u) || m.includes("dash")) return "dash";
      return null;
    }

    function addMedia(raw, source, mime = "") {
      const url = safeUrl(raw);
      if (!url || !/^https?:/i.test(url)) return;
      const kind = classifyMedia(url, mime);
      if (!kind) return;
      if (!media.has(url)) media.set(url, { url, kind, source });
    }

    function addIframe(raw, source) {
      const url = safeUrl(raw);
      if (!url || !/^https?:/i.test(url)) return;
      if (!/(?:youtube(?:-nocookie)?\.com|youtu\.be|vimeo\.com|kaltura\.com|brightcove|players\.brightcove\.net|jwplayer|jwplatform|mux\.com|videodelivery\.net|dailymotion\.com|twitch\.tv)/i.test(url)) return;
      if (!iframeEmbeds.has(url)) iframeEmbeds.set(url, { url, source });
    }

    function noteProvider(text) {
      const s = String(text || "");
      const checks = [
        ["kaltura", /kaltura/i],
        ["jwplayer", /jwplayer|jwplatform/i],
        ["brightcove", /brightcove|videojs-bc/i],
        ["youtube", /youtube(?:-nocookie)?\.com|youtu\.be|ytInitialPlayerResponse/i],
        ["vimeo", /vimeo\.com|player\.vimeo\.com/i],
        ["mux", /stream\.mux\.com|image\.mux\.com/i],
        ["cloudflare-stream", /videodelivery\.net|cloudflarestream/i],
        ["dailymotion", /dailymotion\.com|dai\.ly/i],
        ["twitch", /twitch\.tv|usher\.ttvnw\.net/i],
      ];
      for (const [name, re] of checks) if (re.test(s)) providerHints.add(name);
    }

    function scanText(text, source) {
      if (!text) return;
      let s = String(text)
        .replace(/\\u0026/gi, "&")
        .replace(/\\u002F/gi, "/")
        .replace(/\\\//g, "/")
        .replace(/&amp;/gi, "&");

      noteProvider(s);

      // Absolute direct media/manifests.
      const abs = /https?:\/\/[^"'<>\s]+?(?:\.mp4|\.m4v|\.webm|\.mp3|\.m4a|\.aac|\.ogg|\.opus|\.m3u8|\.mpd)(?:\?[^"'<>\s]*)?/gi;
      let m;
      while ((m = abs.exec(s))) addMedia(m[0], source);

      // Common JSON source/file/url values, including relative media URLs.
      const fields = /["'](?:file|src|source|url|manifestUrl|manifest_url|hls|dash)["']\s*:\s*["']([^"']+)["']/gi;
      while ((m = fields.exec(s))) addMedia(m[1], source);

      // Embed URLs.
      const embeds = /https?:\/\/[^"'<>\s]+?(?:youtube(?:-nocookie)?\.com|youtu\.be|vimeo\.com|kaltura\.com|players\.brightcove\.net|jwplayer|jwplatform|stream\.mux\.com|videodelivery\.net|dailymotion\.com|twitch\.tv)[^"'<>\s]*/gi;
      while ((m = embeds.exec(s))) addIframe(m[0], source);
    }

    function scanDomAndNetwork(sourceTag) {
      try {
        scanText(document.documentElement.innerHTML, sourceTag + ":html");
      } catch (_) {}

      try {
        for (const video of document.querySelectorAll("video, audio")) {
          addMedia(video.currentSrc, sourceTag + ":currentSrc", video.type || "");
          addMedia(video.src, sourceTag + ":src", video.type || "");
          for (const source of video.querySelectorAll("source[src]")) {
            addMedia(source.src, sourceTag + ":source", source.type || "");
          }
        }
      } catch (_) {}

      try {
        for (const iframe of document.querySelectorAll("iframe[src]")) {
          addIframe(iframe.src, sourceTag + ":iframe");
          scanText(iframe.src, sourceTag + ":iframe-url");
        }
      } catch (_) {}

      try {
        for (const entry of performance.getEntriesByType("resource")) {
          addMedia(entry.name, sourceTag + ":performance");
          scanText(entry.name, sourceTag + ":performance-url");
        }
      } catch (_) {}
    }

    function matchedProviderName(name) {
      name = String(name || "").toLowerCase();
      return matched.some((rec) => {
        const hay = `${rec.n} ${rec.m}`.toLowerCase();
        return hay.includes(name);
      });
    }

    function shouldRunProvider(name) {
      return providerHints.has(name) || matchedProviderName(name);
    }

    // ------------------------------------------------------------
    // YouTube: browser-side equivalent of the useful parts of
    // YoutubeIE streamingData extraction.
    //
    // We intentionally do NOT reimplement yt-dlp's player-JS
    // signature/n challenge solver in the page. Instead we use:
    //   1) direct URLs already present in streamingData;
    //   2) HLS/DASH manifests exposed by the player response;
    //   3) already-signed googlevideo URLs observed by the browser.
    // ------------------------------------------------------------
    function youtubeFormatScore(fmt) {
      if (!fmt || typeof fmt !== "object") return -1;
      const height = Number(fmt.height || 0);
      const width = Number(fmt.width || 0);
      const bitrate = Number(fmt.bitrate || fmt.averageBitrate || 0);
      const fps = Number(fmt.fps || 0);
      return height * 1e15 + width * 1e11 + fps * 1e8 + bitrate;
    }

    function youtubeMime(fmt) {
      return String((fmt && fmt.mimeType) || "").split(";", 1)[0].trim();
    }

    function scanYouTubePlayerResponse(pr, source) {
      if (!pr || typeof pr !== "object") return;
      if (seenYouTubePlayerResponses.has(pr)) return;

      const sd = pr.streamingData;
      if (!sd || typeof sd !== "object") return;
      seenYouTubePlayerResponses.add(pr);

      const muxed = Array.isArray(sd.formats) ? sd.formats : [];
      const adaptive = Array.isArray(sd.adaptiveFormats) ? sd.adaptiveFormats : [];

      // Best progressive/muxed format. This is the most useful single-file
      // YouTube archive when the web client exposes a direct URL.
      const directMuxed = muxed
        .filter((f) => f && typeof f.url === "string")
        .sort((a, b) => youtubeFormatScore(b) - youtubeFormatScore(a));
      if (directMuxed.length) {
        addMedia(directMuxed[0].url, `${source}:youtube:muxed`, youtubeMime(directMuxed[0]));
      }

      // Preserve the best separately encoded video and audio too. Modern
      // YouTube often offers the highest resolutions only as adaptive streams.
      const directVideo = adaptive
        .filter((f) => f && typeof f.url === "string" && /^video\//i.test(youtubeMime(f)))
        .sort((a, b) => youtubeFormatScore(b) - youtubeFormatScore(a));
      const directAudio = adaptive
        .filter((f) => f && typeof f.url === "string" && /^audio\//i.test(youtubeMime(f)))
        .sort((a, b) => Number(b.bitrate || 0) - Number(a.bitrate || 0));
      if (directVideo.length) {
        addMedia(directVideo[0].url, `${source}:youtube:adaptive-video`, youtubeMime(directVideo[0]));
      }
      if (directAudio.length) {
        addMedia(directAudio[0].url, `${source}:youtube:adaptive-audio`, youtubeMime(directAudio[0]));
      }

      // yt-dlp also reads these from streamingData. They are preferred over
      // trying to synthesize manifests from segment requests.
      if (typeof sd.hlsManifestUrl === "string") {
        addMedia(sd.hlsManifestUrl, `${source}:youtube:hls`, "application/vnd.apple.mpegurl");
      }
      if (typeof sd.dashManifestUrl === "string") {
        addMedia(sd.dashManifestUrl, `${source}:youtube:dash`, "application/dash+xml");
      }

      // Keep diagnostics for formats that yt-dlp would need to decipher using
      // the current YouTube player JavaScript.
      for (const f of [...muxed, ...adaptive]) {
        if (f && !f.url && (f.signatureCipher || f.cipher)) {
          ctx.state.youtubeCipherFormatsSkipped++;
        }
      }
    }

    function parseYouTubePlayerResponse(value, source) {
      if (!value) return;
      if (typeof value === "object") {
        scanYouTubePlayerResponse(value, source);
        return;
      }
      if (typeof value !== "string") return;
      try {
        const parsed = JSON.parse(value);
        scanYouTubePlayerResponse(parsed, source);
      } catch (_) {}
    }

    function normalizeYouTubePlaybackUrl(raw) {
      const url = safeUrl(raw);
      if (!url) return null;
      try {
        const u = new URL(url);
        if (!/(?:^|\.)googlevideo\.com$/i.test(u.hostname) || !/\/videoplayback(?:$|\/)/i.test(u.pathname)) {
          return url;
        }

        // Browser media requests may be a byte-range/chunk request. The signed
        // core playback URL remains usable without these per-request controls
        // for normal VOD streams, allowing doExternalFetch() to request the
        // complete resource. Do not alter live sequence (sq) URLs.
        if (!u.searchParams.has("sq")) {
          for (const key of ["range", "rn", "rbuf", "ump"]) {
            u.searchParams.delete(key);
          }
        }
        return u.href;
      } catch (_) {
        return url;
      }
    }

    function scanYouTubeNetwork() {
      try {
        for (const entry of performance.getEntriesByType("resource")) {
          const raw = String(entry.name || "");
          if (!raw) continue;

          if (/(?:^|\.)googlevideo\.com\/videoplayback/i.test(raw.replace(/^https?:\/\//i, ""))) {
            let mime = "";
            try {
              const u = new URL(raw);
              mime = u.searchParams.get("mime") || "";
            } catch (_) {}
            const normalized = normalizeYouTubePlaybackUrl(raw);
            if (normalized) addMedia(normalized, "youtube:network:googlevideo", mime);
            continue;
          }

          // YouTube manifest endpoints often do not end in .m3u8/.mpd.
          if (/\/api\/manifest\/hls/i.test(raw)) {
            addMedia(raw, "youtube:network:hls", "application/vnd.apple.mpegurl");
          } else if (/\/api\/manifest\/dash/i.test(raw)) {
            addMedia(raw, "youtube:network:dash", "application/dash+xml");
          }
        }
      } catch (_) {}
    }

    function scanYouTube() {
      if (!shouldRunProvider("youtube")) return;
      ctx.state.youtubeHandlerRuns++;

      try { parseYouTubePlayerResponse(window.ytInitialPlayerResponse, "window.ytInitialPlayerResponse"); } catch (_) {}
      try { parseYouTubePlayerResponse(window.ytplayer && window.ytplayer.config && window.ytplayer.config.args && window.ytplayer.config.args.player_response, "ytplayer.config.args.player_response"); } catch (_) {}
      try { parseYouTubePlayerResponse(window.ytplayer && window.ytplayer.config && window.ytplayer.config.args && window.ytplayer.config.args.raw_player_response, "ytplayer.config.args.raw_player_response"); } catch (_) {}
      try { parseYouTubePlayerResponse(window.ytplayer && window.ytplayer.bootstrapPlayerResponse, "ytplayer.bootstrapPlayerResponse"); } catch (_) {}

      // Some embeds expose the response on configuration objects rather than
      // ytInitialPlayerResponse.
      try {
        const cfg = window.ytplayer && window.ytplayer.config;
        if (cfg && typeof cfg === "object") {
          parseYouTubePlayerResponse(cfg.player_response, "ytplayer.config.player_response");
          parseYouTubePlayerResponse(cfg.raw_player_response, "ytplayer.config.raw_player_response");
        }
      } catch (_) {}

      scanYouTubeNetwork();
    }

    // ------------------------------------------------------------
    // Vimeo: follows VimeoIE._parse_config's core file extraction.
    // Config files contain progressive HTTP files plus HLS/DASH CDN
    // manifests. On player.vimeo.com we can often fetch /config directly.
    // ------------------------------------------------------------
    function vimeoProgressiveScore(fmt) {
      if (!fmt || typeof fmt !== "object") return -1;
      return Number(fmt.height || 0) * 1e15
        + Number(fmt.width || 0) * 1e11
        + Number(fmt.fps || 0) * 1e8
        + Number(fmt.bitrate || 0);
    }

    function scanVimeoConfig(config, source) {
      if (!config || typeof config !== "object") return false;
      if (seenVimeoConfigObjects.has(config)) return false;

      const video = config.video || {};
      const request = config.request || {};
      const files = video.files || request.files || {};
      let found = false;

      const progressive = Array.isArray(files.progressive) ? files.progressive : [];
      const bestProgressive = progressive
        .filter((f) => f && typeof f.url === "string")
        .sort((a, b) => vimeoProgressiveScore(b) - vimeoProgressiveScore(a))[0];
      if (bestProgressive) {
        addMedia(bestProgressive.url, `${source}:vimeo:progressive`, "video/mp4");
        found = true;
      }

      for (const kind of ["hls", "dash"]) {
        const cdns = files[kind] && files[kind].cdns;
        if (!cdns || typeof cdns !== "object") continue;
        const seenUrls = new Set();
        for (const cdn of Object.values(cdns)) {
          let url = cdn && cdn.url;
          if (typeof url !== "string" || !url || seenUrls.has(url)) continue;
          seenUrls.add(url);

          // Vimeo DASH config sometimes points at master.json; yt-dlp resolves
          // json=1 and ultimately downloads master.mpd. Prefer the explicit MPD
          // spelling when it can be derived without an extra JSON request.
          if (kind === "dash" && /\/master\.json(?:$|[?#])/i.test(url) && !/[?&]json=1(?:&|$)/i.test(url)) {
            url = url.replace(/\/master\.json(?=$|[?#])/i, "/master.mpd");
          }
          addMedia(
            url,
            `${source}:vimeo:${kind}`,
            kind === "hls" ? "application/vnd.apple.mpegurl" : "application/dash+xml"
          );
          found = true;
        }
      }

      const liveArchive = video.live_event && video.live_event.archive;
      if (liveArchive && liveArchive.status === "done" && typeof liveArchive.source_url === "string") {
        addMedia(liveArchive.source_url, `${source}:vimeo:live-archive`);
        found = true;
      }

      if (found) {
        seenVimeoConfigObjects.add(config);
        ctx.state.vimeoConfigsFound++;
      }
      return found;
    }

    async function fetchVimeoConfig(rawUrl, source) {
      const url = safeUrl(rawUrl);
      if (!url || seenVimeoConfigUrls.has(url)) return false;
      let host = "";
      try { host = new URL(url).hostname; } catch (_) {}
      if (!/(?:^|\.)vimeo\.com$/i.test(host)) return false;
      seenVimeoConfigUrls.add(url);

      try {
        const response = await fetch(url, {
          method: "GET",
          credentials: "include",
          headers: { Accept: "application/json,text/plain,*/*" },
        });
        if (!response.ok) return false;
        const config = await response.json();
        return scanVimeoConfig(config, source);
      } catch (_) {
        return false;
      }
    }

    function findVimeoConfigUrls() {
      const urls = new Set();
      try {
        for (const el of document.querySelectorAll("[data-config-url]")) {
          if (el.getAttribute("data-config-url")) urls.add(el.getAttribute("data-config-url"));
        }
      } catch (_) {}

      try {
        const html = String(document.documentElement.innerHTML || "")
          .replace(/\\u0026/gi, "&")
          .replace(/\\u002F/gi, "/")
          .replace(/\\\//g, "/")
          .replace(/&amp;/gi, "&");
        let m;
        const configRe = /["']config_url["']\s*:\s*["']([^"']+)["']/gi;
        while ((m = configRe.exec(html))) urls.add(m[1]);
      } catch (_) {}

      try {
        for (const entry of performance.getEntriesByType("resource")) {
          if (/player\.vimeo\.com\/video\/\d+\/config(?:$|[?#])/i.test(entry.name)) urls.add(entry.name);
        }
      } catch (_) {}

      // The player iframe itself has a predictable same-origin config endpoint.
      try {
        const u = new URL(location.href);
        const m = u.pathname.match(/^\/video\/(\d+)(?:\/|$)/);
        if (m && /(?:^|\.)player\.vimeo\.com$/i.test(u.hostname)) {
          const config = new URL(`${u.origin}/video/${m[1]}/config`);
          // Preserve embed privacy/unlisted parameters such as h=...
          for (const [k, v] of u.searchParams) config.searchParams.append(k, v);
          urls.add(config.href);
        }
      } catch (_) {}

      return [...urls];
    }

    async function scanVimeo() {
      if (!shouldRunProvider("vimeo")) return;
      ctx.state.vimeoHandlerRuns++;

      // Current player globals. Vimeo has used several names over time, so keep
      // this intentionally defensive.
      try { scanVimeoConfig(window.playerConfig, "window.playerConfig"); } catch (_) {}
      try { scanVimeoConfig(window.vimeo && window.vimeo.config, "window.vimeo.config"); } catch (_) {}
      try { scanVimeoConfig(window.__PLAYER_CONFIG__, "window.__PLAYER_CONFIG__"); } catch (_) {}

      try {
        const vp = window.vimeo && (window.vimeo.clip_page_config || window.vimeo.vod_title_page_config);
        if (vp && vp.player && vp.player.config_url) {
          await fetchVimeoConfig(vp.player.config_url, "vimeo.page_config");
        }
      } catch (_) {}

      for (const configUrl of findVimeoConfigUrls()) {
        await fetchVimeoConfig(configUrl, "vimeo:config-url");
      }
    }

    // ------------------------------------------------------------
    // JW Player: use the already-evaluated runtime playlist.
    // ------------------------------------------------------------
    function scanJWPlayer() {
      if (!shouldRunProvider("jw") && !shouldRunProvider("jwplayer")) return;
      const jw = window.jwplayer;
      if (typeof jw !== "function") return;

      const seenPlayers = new Set();
      const inspect = (player) => {
        if (!player || seenPlayers.has(player)) return;
        seenPlayers.add(player);
        try {
          const playlist = player.getPlaylist?.();
          if (Array.isArray(playlist)) {
            for (const item of playlist) {
              addMedia(item && (item.file || item.src), "jw:getPlaylist");
              for (const src of (item && item.sources) || []) {
                if (typeof src === "string") addMedia(src, "jw:sources");
                else addMedia(src && (src.file || src.src || src.url), "jw:sources", src && src.type);
              }
            }
          }
        } catch (_) {}
        try {
          const item = player.getPlaylistItem?.();
          if (item) {
            addMedia(item.file || item.src, "jw:getPlaylistItem");
            for (const src of item.sources || []) {
              if (typeof src === "string") addMedia(src, "jw:item:sources");
              else addMedia(src && (src.file || src.src || src.url), "jw:item:sources", src && src.type);
            }
          }
        } catch (_) {}
      };

      try { inspect(jw()); } catch (_) {}
      for (const elem of document.querySelectorAll(".jwplayer[id], [id*='jwplayer']")) {
        try { inspect(jw(elem.id)); } catch (_) {}
      }
    }

    // ------------------------------------------------------------
    // Kaltura: discover partner + entry and query flavorAsset exactly
    // where enough metadata is exposed. This is the TV MIDTVEST path.
    // ------------------------------------------------------------
    function findKalturaPairs() {
      const texts = [];
      try { texts.push(location.href); } catch (_) {}
      try { texts.push(document.documentElement.innerHTML); } catch (_) {}
      try { for (const e of performance.getEntriesByType("resource")) texts.push(e.name); } catch (_) {}
      try { for (const i of document.querySelectorAll("iframe[src]")) texts.push(i.src); } catch (_) {}

      const pairs = [];
      const seen = new Set();
      for (const text of texts) {
        const s = String(text || "").replace(/\\u002F/gi, "/").replace(/\\\//g, "/");
        const partners = new Set();
        const entries = new Set();
        let m;
        const pp = [
          /\/(?:p|partner_id)\/(\d{5,})\b/gi,
          /["'](?:partnerId|partner_id)["']\s*[:=]\s*["']?_?(\d{5,})/gi,
          /["']wid["']\s*[:=]\s*["']_?(\d{5,})/gi,
          /[?&]wid=_?(\d{5,})/gi,
        ];
        const ep = [
          /\/entry_?[Ii]d\/(\d_[A-Za-z0-9]+)/g,
          /[?&]entry_?id=(\d_[A-Za-z0-9]+)/gi,
          /["']entry_?[Ii]d["']\s*[:=]\s*["'](\d_[A-Za-z0-9]+)["']/g,
        ];
        for (const re of pp) while ((m = re.exec(s))) partners.add(m[1]);
        for (const re of ep) while ((m = re.exec(s))) entries.add(m[1]);

        // Known TV MIDTVEST tenant fallback, only in TV MIDTVEST context.
        if (!partners.size && entries.size && /(^|\.)tvmidtvest\.dk$/i.test(location.hostname)) {
          partners.add("1953371");
        }

        for (const p of partners) for (const e of entries) {
          const key = `${p}:${e}`;
          if (!seen.has(key)) {
            seen.add(key);
            pairs.push({ partnerId: p, entryId: e });
          }
        }
      }
      return pairs;
    }

    async function queryKaltura(pair) {
      const key = `${pair.partnerId}:${pair.entryId}`;
      if (seenKalturaEntries.has(key)) return;
      seenKalturaEntries.add(key);

      const payload = {
        apiVersion: "3.3.0",
        clientTag: "html5:v3.1.0",
        format: 1,
        ks: "",
        partnerId: pair.partnerId,
        1: {
          expiry: 86400,
          service: "session",
          action: "startWidgetSession",
          widgetId: `_${pair.partnerId}`,
        },
        2: {
          action: "list",
          filter: { redirectFromEntryId: pair.entryId },
          service: "baseentry",
          ks: "{1:result:ks}",
          responseProfile: {
            type: 1,
            fields: "createdAt,dataUrl,duration,name,plays,thumbnailUrl,userId",
          },
        },
        3: {
          action: "getbyentryid",
          entryId: pair.entryId,
          service: "flavorAsset",
          ks: "{1:result:ks}",
        },
      };

      try {
        const response = await fetch("https://cdnapi.kaltura.com/api_v3/service/multirequest", {
          method: "POST",
          credentials: "omit",
          headers: { "Content-Type": "application/json", Accept: "application/json" },
          body: JSON.stringify(payload),
        });
        if (!response.ok) return;
        const data = await response.json();
        const info = data && data[1] && Array.isArray(data[1].objects) ? data[1].objects[0] : null;
        const flavors = data && data[2] && Array.isArray(data[2].objects) ? data[2].objects : [];
        if (!info || !info.dataUrl || !flavors.length) return;

        const mp4s = flavors.filter((f) => {
          const ext = String(f.fileExt || "mp4").toLowerCase();
          return f && f.id && Number(f.status) === 2 && ext === "mp4";
        }).sort((a, b) =>
          Number(b.height || 0) - Number(a.height || 0) ||
          Number(b.bitrate || 0) - Number(a.bitrate || 0)
        );
        if (!mp4s.length) return;
        const best = mp4s[0];
        let dataUrl = String(info.dataUrl).replace(/\/$/, "");
        if (dataUrl.includes("/flvclipper/")) dataUrl = dataUrl.replace(/\/flvclipper\/.*/, "/serveFlavor");
        addMedia(`${dataUrl}/flavorId/${best.id}`, "kaltura:flavorAsset", "video/mp4");
      } catch (_) {}
    }

    async function runRelevantProviderHandlers() {
      scanYouTube();
      await scanVimeo();
      scanJWPlayer();
      if (shouldRunProvider("kaltura")) {
        for (const pair of findKalturaPairs()) await queryKaltura(pair);
      }
    }

    // ------------------------------------------------------------
    // One-click play fallback. Exactly one candidate is clicked.
    // ------------------------------------------------------------
    function visible(el) {
      if (!(el instanceof Element)) return false;
      const r = el.getBoundingClientRect();
      const s = getComputedStyle(el);
      return r.width > 2 && r.height > 2 && s.display !== "none" && s.visibility !== "hidden" && Number(s.opacity || 1) > 0;
    }

    function playScore(el) {
      if (!visible(el)) return -Infinity;
      if (el.matches("[disabled], [aria-disabled='true']")) return -Infinity;
      const text = `${el.getAttribute("aria-label") || ""} ${el.getAttribute("title") || ""} ${el.getAttribute("data-testid") || ""} ${el.className || ""} ${el.textContent || ""}`.toLowerCase();
      if (/pause|stop|mute|unmute|next|previous|close|luk|annonce|advert/.test(text)) return -Infinity;

      let score = 0;
      if (el.matches("button.tv-hero-play-button")) score += 1000;
      if (el.matches(".vjs-big-play-button, .jw-icon-playback, .ytp-large-play-button, .plyr__control[data-plyr='play']")) score += 900;
      if (el.matches("button[aria-label*='play' i], [role='button'][aria-label*='play' i]")) score += 800;
      if (el.matches("button[title*='play' i], [role='button'][title*='play' i]")) score += 700;
      if (el.matches("button[data-testid*='play' i], [role='button'][data-testid*='play' i]")) score += 650;
      if (el.matches("button[class*='play' i], [role='button'][class*='play' i]")) score += 500;
      if (/\b(?:play|afspil|start video|watch|se video|spela|reproducir|reproduire|lire|abspielen|riproduci|reproduzir)\b/i.test(text)) score += 400;
      if (el.tagName === "BUTTON") score += 50;
      return score;
    }

    function findBestPlayButton() {
      const selectors = [
        "button.tv-hero-play-button",
        ".vjs-big-play-button",
        ".jw-icon-playback",
        ".ytp-large-play-button",
        ".plyr__control[data-plyr='play']",
        "button[aria-label*='play' i]",
        "[role='button'][aria-label*='play' i]",
        "button[title*='play' i]",
        "[role='button'][title*='play' i]",
        "button[data-testid*='play' i]",
        "[role='button'][data-testid*='play' i]",
        "button[class*='play' i]",
        "[role='button'][class*='play' i]",
        "button",
        "[role='button']",
      ];
      const nodes = new Set();
      for (const sel of selectors) {
        try { for (const el of document.querySelectorAll(sel)) nodes.add(el); } catch (_) {}
      }
      return [...nodes]
        .map((el) => ({ el, score: playScore(el) }))
        .filter((x) => Number.isFinite(x.score) && x.score > 0)
        .sort((a, b) => b.score - a.score)[0] || null;
    }

    async function clickOnePlayButton() {
      const best = findBestPlayButton();
      if (!best) return null;
      ctx.state.playButtonFound = true;
      const el = best.el;
      const desc = `${el.tagName.toLowerCase()}${el.id ? "#" + el.id : ""}.${String(el.className || "").trim().split(/\s+/).slice(0, 3).join(".")}`;
      try {
        if (typeof scrollAndClick === "function") {
          await scrollAndClick(el, 300, { block: "center", inline: "center", behavior: "instant" });
        } else {
          el.scrollIntoView({ block: "center", inline: "center", behavior: "instant" });
          await sleep(300);
          el.click();
        }
        ctx.state.playButtonClicked = true;
        return desc;
      } catch (_) {
        try {
          el.click();
          ctx.state.playButtonClicked = true;
          return desc;
        } catch (_) {
          return null;
        }
      }
    }

    async function waitForPlayerChange(resourcesBefore, iframeCountBefore, videoCountBefore) {
      const started = Date.now();
      while (Date.now() - started < 10000) {
        try {
          if (document.querySelectorAll("iframe").length > iframeCountBefore) return "new iframe";
          if (document.querySelectorAll("video, audio").length > videoCountBefore) return "new media element";
          for (const e of performance.getEntriesByType("resource")) {
            if (!resourcesBefore.has(e.name) && /video|player|embed|manifest|m3u8|mpd|mp4|kaltura|brightcove|jwplayer|vimeo|youtube|googlevideo|mux|videodelivery/i.test(e.name)) {
              return `new media resource: ${e.name}`;
            }
          }
        } catch (_) {}
        await sleep(250);
      }
      return null;
    }

    async function* archiveDiscovered() {
      let fetchedAny = false;

      // Add provider iframe/embed URLs so Browsertrix can crawl the actual player context too.
      for (const item of iframeEmbeds.values()) {
        if (typeof addLink === "function") {
          try {
            await addLink(item.url);
            ctx.state.iframeEmbedsFound++;
          } catch (_) {}
        }
      }

      for (const item of media.values()) {
        if (item.kind === "file") ctx.state.directFilesFound++;
        else ctx.state.manifestsFound++;

        if (typeof doExternalFetch === "function") {
          try {
            const ok = await doExternalFetch(item.url);
            if (ok) {
              ctx.state.fetched++;
              fetchedAny = true;
              yield getState(ctx, `YT-DLP Universal: fetched ${item.kind} [${item.source}] ${item.url}`);
              continue;
            }
          } catch (_) {}
        }

        if (typeof addLink === "function") {
          try {
            await addLink(item.url);
            yield getState(ctx, `YT-DLP Universal: queued ${item.kind} [${item.source}] ${item.url}`);
          } catch (_) {}
        }
      }

      return fetchedAny;
    }

    // ============================================================
    // PASS 1: no interaction.
    // ============================================================
    scanDomAndNetwork("initial");
    await runRelevantProviderHandlers();
    scanDomAndNetwork("initial-provider");

    // ============================================================
    // PASS 2: click one play button if no direct file is exposed yet.
    // A manifest alone does not suppress the click: starting the player can reveal
    // signed stream/segment URLs (especially on YouTube/live streams).
    // This intentionally mirrors the TV MIDTVEST lesson: the click may merely
    // mount a popover/player; successful playback is NOT required.
    // ============================================================
    const hasDirectFileBeforeClick = [...media.values()].some((item) => item.kind === "file");
    if (!hasDirectFileBeforeClick) {
      const resourcesBefore = new Set();
      try { for (const e of performance.getEntriesByType("resource")) resourcesBefore.add(e.name); } catch (_) {}
      const iframeCountBefore = document.querySelectorAll("iframe").length;
      const videoCountBefore = document.querySelectorAll("video, audio").length;

      const clicked = await clickOnePlayButton();
      if (clicked) {
        yield getState(ctx, `YT-DLP Universal: clicked one play candidate: ${clicked}`);
        const reason = await waitForPlayerChange(resourcesBefore, iframeCountBefore, videoCountBefore);
        if (reason) {
          ctx.state.playerChangeDetected = true;
          yield getState(ctx, `YT-DLP Universal: player change detected: ${reason}`);
        }

        if (typeof waitForNetworkIdle === "function") {
          try {
            await Promise.race([waitForNetworkIdle(750, 2), sleep(4000)]);
          } catch (_) {}
        } else {
          await sleep(2000);
        }

        scanDomAndNetwork("after-click");
        await runRelevantProviderHandlers();
        scanDomAndNetwork("after-click-provider");
      }
    }

    ctx.state.providerHints = [...providerHints].sort();

    if (ctx.state.providerHints.length) {
      yield getState(ctx, "YT-DLP Universal: provider hints: " + ctx.state.providerHints.join(", "));
    }

    if (!media.size && !iframeEmbeds.size) {
      yield getState(ctx, "YT-DLP Universal: no direct media, manifest, or known player iframe discovered");
      return;
    }

    // Yield through the async generator manually so Browsertrix receives progress messages.
    const gen = archiveDiscovered();
    let step = await gen.next();
    while (!step.done) {
      yield step.value;
      step = await gen.next();
    }

    yield getState(
      ctx,
      `YT-DLP Universal: done; direct=${ctx.state.directFilesFound}, manifests=${ctx.state.manifestsFound}, embeds=${ctx.state.iframeEmbedsFound}, fetched=${ctx.state.fetched}, youtubeRuns=${ctx.state.youtubeHandlerRuns}, vimeoRuns=${ctx.state.vimeoHandlerRuns}`
    );
  }
}
